baseurl: "/"
title: "Welcome to qaqLand!"
author:
  name: qaqland
  email: qaq@qaq.land

# theme special, don't change
disableKinds:
  - taxonomy
  # - page
  # - home
  - section
  - taxonomy
  - term
  # - RSS
  - sitemap
  - robotsTXT
  - "404"
outputs:
  home:
    - HTML
    - RSS
  page:
    # - HTML
    - RSS
